### ISSUE TITLE
udev rule and ebsnvme-id missing in Oracle Linux

### ISSUE THREAD

**Issue by donnmch** [amazonlinux/amazon-ec2-utils#35]
udev rule and python program ebsnvme-id are missing in package nvme-cli on Oracle Linux, this is causing proper device names mapping (e.g., /dev/sd*) not working when compared to  other Linux OS running on AWS.

If rules are manually created together with python program /sbin/ebsnvme-id, they work properly on OEL

**Comment by lasith-kg** [comment]
I believe `ebsnvme-id` is provided from the AMI level and not as a separately installed package. The  Amazon Linux AMI 2017.09.01 or later (including Amazon Linux 2) and Free BSD AMIs are the only ones to include it by default.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html#identify-nvme-ebs-device

You should use this tool I developed called [ebs-bootstrap](https://github.com/reecetech/ebs-bootstrap). I ported the code from `ebsnvme-id` to Go and wrapped it around some logic to manage block devices as code.

With this tool you can manage EBS and Instance Store volumes as-code (formatting, mounting, resizing). It currently supports the `xfs` and `ext4` file system.

Affiliation: I am a major contribute to `ebs-bootstrap`

**Comment by nmeyerhans** [comment]
I don't know what .spec file Oracle Linux is using to build its RPM, but the .spec in this repository installs it (see [line 69](https://github.com/amazonlinux/amazon-ec2-utils/blob/main/amazon-ec2-utils.spec#L69))

This issue should probably be reported to the maintainers of the Oracle Linux AMIs, but I'm not sure who that is or how to reach them.

In an ideal world, the ebsnvme-id logic would be re-implemented in C and incorporated directly into systemd.  That'd make this functionality available more widely and more consistently.

**Comment by lasith-kg** [comment]
Hey @nmeyerhans!

> In an ideal world, the ebsnvme-id logic would be re-implemented in C

Regarding this, I actually made an attempt at converting the `ebs-nvmeid` from Python to native-code (albeit not through a C-based approach). I created [ebs-bootstrap](https://github.com/reecetech/ebs-bootstrap/tree/main) a tool to manage EBS and Instance Store NVMe devices through an as-code approach. 

```
[~] sudo ebs-bootstrap -mode=prompt
🔵 Nitro NVMe detected: /dev/nvme1n1 -> /dev/sdb
🔵 Nitro NVMe detected: /dev/nvme2n1 -> /dev/sdh
🟠 Formatting larger disks can take several seconds ⌛
🟣 Would you like to format /dev/nvme1n1 to ext4? (y/n): y
⭐ Successfully formatted /dev/nvme1n1 to ext4
🟠 Certain file systems require that devices be unmounted prior to labeling
🟣 Would you like to label device /dev/nvme1n1 to 'stateful'? (y/n): y
⭐ Successfully labelled /dev/nvme1n1 to 'stateful'
...
🟣 Would you like to change ownership (1000:1000) of /mnt/ebs? (y/n): y
⭐ Successfully changed ownership (1000:1000) of /mnt/ebs
🟢 Passed all validation checks
```

The code itself is programmed in Go-lang and then built for `arm64` and `x86_64`. Since it is compiled to a statically compiled binary it will support all flavors of Linux (RHEL, Amazon LInux, Oracle Linux, ...) Essentially you provide the original block device mapping and some configuration around the ideal file system, where the volume should be mounted and who should own the mount point. 

This is the [logic](https://github.com/reecetech/ebs-bootstrap/blob/main/internal/service/nvme.go) that I ported from `ebs-nvmeid`. It not only supports extracting the block device mapping from **EBS volumes** but also **Instance Store** volumes.

@donnmch this might not be the right solution for you since you were specifically looking for `udev` rules. However, you still might some find some use from it as it can be installed through a simple `curl` and `install` command.
